'use client';
import { useEffect, useState } from 'react';

type Product = { id: string; name: string; sku: string; costPrice: number };
type Supplier = { id: string; name: string };
type Line = { productId: string; quantity: string; unitCost: string };

export default function PurchasesPage() {
  const [products, setProducts] = useState<Product[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [lines, setLines] = useState<Line[]>([{ productId: '', quantity: '1', unitCost: '' }]); const [supplierId, setSupplierId] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/purchases/options').then(r => r.json()).then(data => { setProducts(data.products || []); setSuppliers(data.suppliers || []); }); }, []);
  function updateLine(index: number, field: keyof Line, value: string) { setLines(lines.map((line, i) => i === index ? { ...line, [field]: value } : line)); }
  function selectProduct(index: number, value: string) { const product = products.find(p => p.id === value); updateLine(index, 'productId', value); if (product) updateLine(index, 'unitCost', String(product.costPrice)); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); setMessage(''); const res = await fetch('/api/purchases', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ supplierId: supplierId || null, items: lines.map(l => ({ productId: l.productId, quantity: Number(l.quantity), unitCost: Number(l.unitCost) })) }) }); const data = await res.json(); if (!res.ok) { setError(data.error); return; } setMessage('Compra registrada y stock actualizado.'); setLines([{ productId: '', quantity: '1', unitCost: '' }]); setSupplierId(''); }
  const total = lines.reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.unitCost || 0), 0);
  return <div className="p-6 md:p-10"><p className="text-sm font-semibold text-brand-600">Compras</p><h1 className="mt-1 text-3xl font-bold">Registrar compra</h1><form onSubmit={submit} className="mt-8 max-w-4xl rounded-2xl bg-white p-6 shadow-soft"><label className="block max-w-sm text-sm font-semibold">Proveedor<select value={supplierId} onChange={e => setSupplierId(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3"><option value="">Proveedor general</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="mt-6 space-y-3">{lines.map((line, index) => <div key={index} className="grid gap-3 md:grid-cols-[1fr_120px_140px_auto]"><select required value={line.productId} onChange={e => selectProduct(index, e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3"><option value="">Selecciona producto</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input required min="1" type="number" value={line.quantity} onChange={e => updateLine(index, 'quantity', e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3" placeholder="Cantidad" /><input required min="0" step="0.01" type="number" value={line.unitCost} onChange={e => updateLine(index, 'unitCost', e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3" placeholder="Costo" /><button type="button" disabled={lines.length === 1} onClick={() => setLines(lines.filter((_, i) => i !== index))} className="rounded-xl bg-red-50 px-3 font-bold text-red-600 disabled:opacity-40">×</button></div>)}</div><button type="button" onClick={() => setLines([...lines, { productId: '', quantity: '1', unitCost: '' }])} className="mt-4 text-sm font-bold text-brand-600">+ Agregar producto</button><div className="mt-6 flex flex-wrap items-center justify-between gap-4 border-t pt-5"><strong className="text-xl">Total: ${total.toFixed(2)}</strong><button className="rounded-xl bg-brand-600 px-6 py-3 font-bold text-white hover:bg-brand-700">Confirmar compra</button></div>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}{message && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-600">{message}</p>}</form></div>;
}
